### ISSUE TITLE
YAAP A13 not booting

### ISSUE THREAD

**Issue by realahnet** [ItsLynix/xdroid_patch#2]
the new YAAP gsi that popped up in the gsi list pointed me to this github page. its not booting for me. all the other ones did. wierd. i am stock android 11 one ui 3.1 firmware for galaxy A32 4G. with one ui 4.1 vendor no A13 gsi boots.

**Comment by SelynCatto** [comment]
Did you say you are not able to boot any A13 gsi at all? (e.g sparkos, lineage, etc.)

Anyhow, let's collect some logs.
Connect your phone to your PC with adb installed.
When you reach the Samsung boot splash, run `adb -d logcat > logcat.log` 
If nothing happens, then it may be that adb isn't working at all. If that's the case, boot to recovery and run the `adb pull` command to get these (or similarly named) files.

```
/sys/fs/pstore/console-ramoops-0
/proc/last_kmsg
/proc/kmsg
```

And kindly attach the files you gathered in this issue.

**Comment by realahnet** [comment]
no every other A13 gsi was sucessfully booting so far. although i have to use android 11 vendor. i'll try getting logs once i get home

**Comment by SelynCatto** [comment]
Alright thanks!

**Comment by realahnet** [comment]
> Alright thanks!

uh i use dsu sideloader to test this. i am currently running rice droid 5.0 and i would not like to remove it... i dont think i can pull the files generated when this gsi booted with dsu?

**Comment by SelynCatto** [comment]
Alright, I'm currently working on a build with reworked patches, I'll let you know when it's done and you can test it with dsu sideloader.

**Comment by realahnet** [comment]
> Alright, I'm currently working on a build with reworked patches, I'll let you know when it's done and you can test it with dsu sideloader.

i see the new YAAP GSI is up. i'll give it a test with dsu.

**Comment by realahnet** [comment]
> > Alright, I'm currently working on a build with reworked patches, I'll let you know when it's done and you can test it with dsu sideloader.
> 
> i see the new YAAP GSI is up. i'll give it a test with dsu.

just tried it. it still didnt boot. why doesnt anything work for me. is this something similar happening to users with PE GSI? it didnt boot on every device having a MTK chipset.

**Comment by ghost** [comment]
> > > Alright, I'm currently working on a build with reworked patches, I'll let you know when it's done and you can test it with dsu sideloader.
> > 
> > 
> > i see the new YAAP GSI is up. i'll give it a test with dsu.
> 
> just tried it. it still didnt boot. why doesnt anything work for me. is this something similar happening to users with PE GSI? it didnt boot on every device having a MTK chipset.

This is a known issue, related to **BPF** on Mediatek chipsets.
Your device has the same chipset as mine (Mediatek Helio G80).

**This is some information from my device's custom ROM developer.**
![Screenshot_20221030-004821](https://user-images.githubusercontent.com/116973792/198847621-d903f1b1-d276-4c87-8872-602993696617.png)
![Screenshot_20221030-004736](https://user-images.githubusercontent.com/116973792/198847630-0ea8436e-3f76-48f9-b8c1-7caa3aafb2ef.png)



**Also discussed in telegram treble droid builder.**
![Screenshot_20221030-013410](https://user-images.githubusercontent.com/116973792/198847790-ff9011a6-a719-46d5-b246-413d58f0620e.png)

**Comment by realahnet** [comment]
> > > > Alright, I'm currently working on a build with reworked patches, I'll let you know when it's done and you can test it with dsu sideloader.
> > > 
> > > 
> > > i see the new YAAP GSI is up. i'll give it a test with dsu.
> > 
> > 
> > just tried it. it still didnt boot. why doesnt anything work for me. is this something similar happening to users with PE GSI? it didnt boot on every device having a MTK chipset.
> 
> This is a known issue, related to **BPF** on Mediatek chipsets. Your device has the same chipset as mine (Mediatek Helio G80).
> 
> **This is some information from my device's custom ROM developer.** ![Screenshot_20221030-004821](https://user-images.githubusercontent.com/116973792/198847621-d903f1b1-d276-4c87-8872-602993696617.png) ![Screenshot_20221030-004736](https://user-images.githubusercontent.com/116973792/198847630-0ea8436e-3f76-48f9-b8c1-7caa3aafb2ef.png)
> 
> **Also discussed in telegram treble droid builder.** ![Screenshot_20221030-013410](https://user-images.githubusercontent.com/116973792/198847790-ff9011a6-a719-46d5-b246-413d58f0620e.png)

oh. other gsi's did work fine and i am using Android 11 vendor that maybe the reason why the other android 13 gsi's didnt boot on android 12 vendor. the new patches that phh sent are the patches included in this new build? and does it boot for you. thanksss well if not hope it gets resolved soon

**Comment by SelynCatto** [comment]
I do not use the latest trebledroid patches, but I can merge the bpf patch in and we'll see

**Comment by SelynCatto** [comment]
@captaincookie200 @1percentpositive 
Do you mind joining my telegram group https://t.me/lynixgsi or messaging me https://t.me/lynixfox for testing? Thanks

**Comment by SelynCatto** [comment]
About to try out these patches 26be85f01879a0556701d459ab39c812fea67bf6

**Comment by realahnet** [comment]
> @captaincookie200 @1percentpositive Do you mind joining my telegram group https://t.me/lynixgsi or messaging me https://t.me/lynixfox for testing? Thanks

telegram is banned in my country i have no idea why. using a vpn is just pain. but i'll try. do you have anywhere else we could contact? otherwise i'll try with a vpn

**Comment by SelynCatto** [comment]
> > @captaincookie200 @1percentpositive Do you mind joining my telegram group https://t.me/lynixgsi or messaging me https://t.me/lynixfox for testing? Thanks
> 
> telegram is banned in my country i have no idea why. using a vpn is just pain. but i'll try. do you have anywhere else we could contact? otherwise i'll try with a vpn

If you have discord, contact at Lynix#0015

**Comment by SelynCatto** [comment]
We know this is fixed now guys! Have fun!
